import { createFileRoute,useRouter } from "@tanstack/react-router";
import {SiteFooter,SiteHeader,useSiteMotion} from "@/components/SiteChrome";
import {CapabilityCards} from "@/components/rckt/SystemBlocks";
import SystemCards,{type SystemCardData} from "@/components/rckt/SystemCards";
import SystemFinalCta from "@/components/rckt/SystemFinalCta";
import SystemPageHero from "@/components/rckt/SystemPageHero";
import SystemSection from "@/components/rckt/SystemSection";
const SITE_URL="https://rckt-latam.lovable.app";
const SYSTEMS:SystemCardData[]=[{badge:"S1",kicker:"Sistema 01",title:"Generación de demanda medida hasta la venta",shortName:"Demand System",desc:"Performance Media · Creative Performance · Search & AI Visibility · medición del clic al cierre.",href:"/sistemas/demand-system",art:"demand"},{badge:"S2",kicker:"Sistema 02",title:"De lead a venta sin fugas",shortName:"Sales Flow",desc:"Pauta, WhatsApp y CRM conectados, con respuesta, seguimiento y dueño para cada prospecto.",href:"/sistemas/sales-flow",art:"sales"},{badge:"S3",kicker:"Sistema 03",title:"Procesos que se ejecutan solos, con supervisión",shortName:"Operations System",desc:"Automatización de procesos repetitivos, medidos contra una línea base y con aprobación humana.",href:"/sistemas/operations-system",art:"operations"}];
const ACCESOS=[{titulo:"Revenue Diagnostic",detalle:"Antes de tocar nada, medimos.",href:"/sistemas/revenue-diagnostic"},{titulo:"Demand System",detalle:"Generación de demanda medida hasta la venta.",href:"/sistemas/demand-system"},{titulo:"Sales Flow",detalle:"De lead a venta sin fugas.",href:"/sistemas/sales-flow"},{titulo:"Operations System",detalle:"Procesos que se ejecutan solos, con supervisión.",href:"/sistemas/operations-system"},{titulo:"Revenue Engine",detalle:"El sistema completo de captación a cierre.",href:"/sistemas/revenue-engine"}];
export const Route=createFileRoute("/sistemas/")({staticData:{sitemap:true},head:()=>({meta:[{title:"Sistemas — RCKT"},{name:"description",content:"Tres sistemas, no más: Demand System, Sales Flow y Operations System. Combinados son Revenue Engine y Growth OS."},{property:"og:title",content:"Sistemas — RCKT"},{property:"og:description",content:"Si algo no cabe en uno de los tres, no lo vendemos."},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL+"/sistemas"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:SITE_URL+"/sistemas"}]}),component:SistemasPage,errorComponent:SistemasError,notFoundComponent:()=> <SistemasError/>});
function SistemasPage(){useSiteMotion([]);return <div className="rckt-site tcn-page"><main id="top">
<SystemPageHero label="Sistemas" title={<>Tres sistemas, no <em>más</em>.</>} promise="Si algo no cabe en uno de los tres, no lo vendemos."/>
<SystemSection id="ecuacion" num="01." label="Arquitectura" title={<>Cinco puertas, una sola cadena de <em className="font-serif-accent">ingresos</em>.</>} phrase="Los sistemas se combinan cuando la operación está lista."><div className="system-architecture"><div className="arch-row"><span className="arch-node">Demand System</span><span className="arch-sign">+</span><span className="arch-node">Sales Flow</span><span className="arch-sign">=</span><span className="arch-result">Revenue Engine</span></div><div className="arch-row"><span className="arch-node">Revenue Engine</span><span className="arch-sign">+</span><span className="arch-node">Operations</span><span className="arch-sign">=</span><span className="arch-result">Growth OS <small>solo para cuentas maduras</small></span></div></div></SystemSection>
<SystemSection id="sistemas" num="02." label="Los tres sistemas" title="Elige por la fuga, no por el nombre." phrase="Demand, Sales Flow y Operations cubren la cadena completa."><SystemCards systems={SYSTEMS}/></SystemSection>
<SystemSection id="lista" num="03." label="Cinco accesos" title={<>Los sistemas crecen cuando la cuenta está <em className="font-serif-accent">lista</em>.</>} phrase="Cada puerta responde a un punto distinto de la operación."><CapabilityCards items={ACCESOS.map(x=>({...x,linkLabel:"Ver sistema →"}))}/></SystemSection>
<SystemFinalCta title={<>Toda cuenta empieza por el <em className="font-serif-accent">diagnóstico</em>.</>}/>
</main><SiteFooter/></div>}
function SistemasError(){const router=useRouter();return <div className="rckt-site tcn-page"><SiteHeader/><main className="band"><div className="container"><div className="form-card" role="alert"><span className="kicker">Sistemas</span><h1>No pudimos mostrar esta página.</h1><p>Intenta cargarla nuevamente. Si el problema continúa, puedes volver al inicio.</p><div className="form-actions"><button className="btn btn-primary" type="button" onClick={()=>void router.invalidate()}>Intentar de nuevo</button><a className="btn" href="/">Volver al inicio</a></div></div></div></main><SiteFooter/></div>}
