import { createFileRoute, useRouter } from "@tanstack/react-router";
import { SiteFooter, SiteHeader, useSiteMotion } from "@/components/SiteChrome";
import FaqSection, { faqJsonLd, type FaqItem } from "@/components/rckt/FaqSection";
import { AcceptanceSteps, CapabilityCards, RuleList } from "@/components/rckt/SystemBlocks";
import SystemFinalCta from "@/components/rckt/SystemFinalCta";
import SystemPageHero from "@/components/rckt/SystemPageHero";
import SystemSection from "@/components/rckt/SystemSection";
const SITE_URL="https://rckt-latam.lovable.app";
const COMPONENTES=[{titulo:"Sales Flow núcleo",detalle:"Ads ↔ WhatsApp Business API ↔ CRM, routing y asignación a asesores, calificación con agente supervisado, SLAs, secuencias, gestión de inasistencia, atribución offline."},{titulo:"Conversational Revenue",detalle:"Agentes con aprobación humana en toda decisión de venta."},{titulo:"CRM & RevOps",detalle:"El proceso comercial vive en un solo lugar."},{titulo:"Conversion Platforms",detalle:"Landing, web, ecommerce, siempre con tracking y CRM conectados."}];
const FAQS: FaqItem[]=[
  {question:"¿Necesito que me hagan una página web nueva para que Sales Flow funcione?",answer:"No necesariamente, pero si haces una web con nosotros, siempre va conectada a tracking y CRM — una web sin eso es decoración, y no la vendemos así."},
  {question:"¿Un agente de WhatsApp con IA puede cerrarle una venta a un cliente sin que un humano intervenga?",answer:"Nunca. Un agente nunca cierra una venta ni promete condiciones sin aprobación humana."},
  {question:"¿En cuánto tiempo queda funcionando la integración de WhatsApp, campañas y CRM?",answer:"Máximo 30 días desde el inicio del setup."},
  {question:"¿Sales Flow reemplaza mi CRM actual o se conecta con el que ya tengo?",answer:"Se conecta. Tu CRM es la fuente de verdad; lo configuramos y lo conectamos, no lo sustituimos."},
  {question:"¿Qué necesito tener listo antes de implementar Sales Flow?",answer:"Un número de WhatsApp Business API verificado, un CRM (o migramos si hace falta), y un equipo comercial con un responsable nombrado."},
];
export const Route=createFileRoute("/sistemas/sales-flow")({staticData:{sitemap:true},head:()=>({meta:[{title:"Sales Flow — RCKT"},{name:"description",content:"De lead a venta sin fugas: pauta, WhatsApp y CRM conectados, con respuesta, seguimiento y dueño para cada prospecto."},{property:"og:title",content:"Sales Flow — RCKT"},{property:"og:description",content:"La web nunca se vende sola."},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL+"/sistemas/sales-flow"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:SITE_URL+"/sistemas/sales-flow"}],scripts:FAQS.length>0?[faqJsonLd(FAQS)]:[]}),component:SalesFlowPage,errorComponent:SalesFlowError,notFoundComponent:()=> <SalesFlowError/>});
function SalesFlowPage(){useSiteMotion([]);return <div className="rckt-site tcn-page"><main id="top">
<SystemPageHero label="Sales Flow" title={<>De lead a venta sin <em>fugas</em>.</>} promise="Hoy pagas por un prospecto, te escribe por WhatsApp, y ahí empieza a perderse: respuesta tarde, sin seguimiento, fuera del CRM. Sales Flow conecta tu pauta, WhatsApp y CRM para que cada prospecto tenga respuesta, seguimiento y dueño —y para que sepas cuáles compran."/>
<SystemSection num="01." label="El problema" title={<>El prospecto llega. La fuga empieza <em className="font-serif-accent">después</em>.</>} phrase="Respuesta tarde, sin seguimiento y conversaciones fuera del CRM."><p className="system-section__lead">Hoy pagas por un prospecto, te escribe por WhatsApp, y ahí empieza a perderse: respuesta tarde, sin seguimiento, fuera del CRM.</p></SystemSection>
<SystemSection id="componentes" num="02." label="Qué incluye" title={<>Cada prospecto con respuesta, seguimiento y <em className="font-serif-accent">dueño</em>.</>} phrase="Pauta, WhatsApp, CRM y atribución conectados en un solo flujo."><CapabilityCards items={COMPONENTES}/></SystemSection>
<SystemSection num="03." label="Qué no incluye" title={<>Conectar la venta no significa hacerlo <em className="font-serif-accent">todo</em>.</>} phrase="Sales Flow ordena el recorrido comercial; otras capacidades pertenecen a otros sistemas."><RuleList items={["Inversión en pauta", "Gestión de campañas", "Operación de cierre por parte de RCKT", "Licencias de CRM y WhatsApp Business API"]}/></SystemSection>
<SystemSection id="regla" num="04." label="Regla" title={<>La web nunca se vende <em className="font-serif-accent">sola</em>.</>} phrase="La conversión ocurre cuando el sistema acompaña la conversación humana."><div className="system-highlight"><p>La web nunca se vende sola.</p></div><p className="system-note">Esta es la página más visitada desde campañas en Latinoamérica.</p></SystemSection>
<SystemSection id="para-quien" num="05." label="Para quién" title={<>Cuando vender exige una conversación <em className="font-serif-accent">humana</em>.</>} phrase="Negocios donde la venta pasa por una persona, pero el sistema evita que el prospecto se pierda."><RuleList items={["Negocios donde la venta pasa por conversación humana"]}/></SystemSection>
<SystemSection num="06." label="Cómo empieza" title={<>Probamos el flujo completo con prospectos <em className="font-serif-accent">reales</em>.</>} phrase="La aceptación exige trazabilidad, respuesta y asignación funcionando."><AcceptanceSteps plazo="Sistema aceptado en máximo 30 días" items={[{texto:"Pauta, WhatsApp Business API y CRM conectados"},{texto:"Flujo probado con prospectos reales"},{texto:"Todos los prospectos entran al CRM con su origen"}]}/></SystemSection>
<FaqSection items={FAQS}/><SystemFinalCta/>
</main><SiteFooter/></div>}
function SalesFlowError(){const router=useRouter();return <div className="rckt-site tcn-page"><SiteHeader/><main className="band"><div className="container"><div className="form-card" role="alert"><span className="kicker">Sales Flow</span><h1>No pudimos mostrar esta página.</h1><p>Intenta cargarla nuevamente. Si el problema continúa, puedes volver al inicio.</p><div className="form-actions"><button className="btn btn-primary" type="button" onClick={()=>void router.invalidate()}>Intentar de nuevo</button><a className="btn" href="/">Volver al inicio</a></div></div></div></main><SiteFooter/></div>}
