import { createFileRoute, useRouter } from "@tanstack/react-router";
import { Calendar, CalendarCheck, Database, Monitor, MessagesSquare, Target, Users, Workflow } from "lucide-react";
import { SiteFooter, SiteHeader, useSiteMotion } from "@/components/SiteChrome";
import FaqSection, { faqJsonLd, type FaqItem } from "@/components/rckt/FaqSection";
import GeneralCta from "@/components/rckt/GeneralCta";
import SystemPageHero from "@/components/rckt/SystemPageHero";
const SITE_URL="https://rckt-latam.lovable.app";
const COMPONENTES=[{titulo:"Sales Flow núcleo",detalle:"Ads ↔ WhatsApp Business API ↔ CRM, routing y asignación a asesores, calificación con agente supervisado, SLAs, secuencias, gestión de inasistencia, atribución offline."},{titulo:"Conversational Revenue",detalle:"Agentes con aprobación humana en toda decisión de venta."},{titulo:"CRM & RevOps",detalle:"El proceso comercial vive en un solo lugar."},{titulo:"Conversion Platforms",detalle:"Landing, web, ecommerce, siempre con tracking y CRM conectados."}];
const COMPONENT_ICONS=[Workflow,MessagesSquare,Database,Monitor];
const STATS=[
  {label:"Para quién",detail:"Negocios donde la venta pasa por conversación humana",Icon:Users},
  {label:"Cadencia",detail:"Seguimiento de SLAs y fugas",Icon:Calendar},
  {label:"Compromiso mínimo",detail:"Sistema aceptado en máximo 30 días",Icon:CalendarCheck},
  {label:"Qué mide el éxito",detail:"Respuesta, seguimiento, atribución y cierre",Icon:Target},
];
const FAQS: FaqItem[]=[
  {question:"¿Necesito que me hagan una página web nueva para que Sales Flow funcione?",answer:"No necesariamente, pero si haces una web con nosotros, siempre va conectada a tracking y CRM — una web sin eso es decoración, y no la vendemos así."},
  {question:"¿Un agente de WhatsApp con IA puede cerrarle una venta a un cliente sin que un humano intervenga?",answer:"Nunca. Un agente nunca cierra una venta ni promete condiciones sin aprobación humana."},
  {question:"¿En cuánto tiempo queda funcionando la integración de WhatsApp, campañas y CRM?",answer:"Máximo 30 días desde el inicio del setup."},
  {question:"¿Sales Flow reemplaza mi CRM actual o se conecta con el que ya tengo?",answer:"Se conecta. Tu CRM es la fuente de verdad; lo configuramos y lo conectamos, no lo sustituimos."},
  {question:"¿Qué necesito tener listo antes de implementar Sales Flow?",answer:"Un número de WhatsApp Business API verificado, un CRM (o migramos si hace falta), y un equipo comercial con un responsable nombrado."},
];
export const Route=createFileRoute("/sistemas/sales-flow")({staticData:{sitemap:true},head:()=>({meta:[{title:"Sales Flow — RCKT"},{name:"description",content:"De lead a venta sin fugas: pauta, WhatsApp y CRM conectados, con respuesta, seguimiento y dueño para cada prospecto."},{property:"og:title",content:"Sales Flow — RCKT"},{property:"og:description",content:"La web nunca se vende sola."},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL+"/sistemas/sales-flow"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:SITE_URL+"/sistemas/sales-flow"}],scripts:FAQS.length>0?[faqJsonLd(FAQS)]:[]}),component:SalesFlowPage,errorComponent:SalesFlowError,notFoundComponent:()=> <SalesFlowError/>});
function SalesFlowPage(){useSiteMotion([]);return <div className="rckt-site tcn-page"><main id="top">
<SystemPageHero label="Sales Flow" title={<>De lead a venta sin <em>fugas</em>.</>} context="Hoy pagas por un prospecto, te escribe por WhatsApp, y ahí empieza a perderse: respuesta tarde, sin seguimiento, fuera del CRM. Sales Flow conecta tu pauta, WhatsApp y CRM para que cada prospecto tenga respuesta, seguimiento y dueño —y para que sepas cuáles compran."/>
<section className="system-composition system-stats"><div className="container system-stat-grid">{STATS.map(({label,detail,Icon})=><article className="system-stat-card" key={label}><span className="system-icon"><Icon aria-hidden="true"/></span><p className="label-orange">{label}</p><p>{detail}</p></article>)}</div></section>
<section className="system-composition system-warm" id="componentes"><div className="container"><div className="system-composition__heading"><span className="label-orange">Qué incluye</span><h2>Cada prospecto con respuesta, seguimiento y <em className="font-serif-accent">dueño</em>.</h2><p>Pauta, WhatsApp, CRM y atribución conectados en un solo flujo.</p></div><div className="sales-flow-grid">{COMPONENTES.map((item,index)=>{const Icon=COMPONENT_ICONS[index];return <article className={index===0?"sales-flow-card sales-flow-card--core":"sales-flow-card"} key={item.titulo}><span className="system-icon"><Icon aria-hidden="true"/></span><span className="sales-flow-card__index">{String(index+1).padStart(2,"0")}</span><h3>{item.titulo}</h3><p>{item.detalle}</p></article>})}</div><aside className="system-orange-band"><span className="label-on-orange">Qué no incluye</span><h3>Conectar la venta no significa hacerlo todo.</h3><p>Sales Flow ordena el recorrido comercial; otras capacidades pertenecen a otros sistemas.</p><small>Inversión en pauta · Gestión de campañas · Operación de cierre por parte de RCKT · Licencias de CRM y WhatsApp Business API</small></aside></div></section>
<section className="sales-rule-band" id="regla"><div className="container"><span className="label-orange">Regla</span><p>La web nunca se vende <em>sola</em>.</p><small>La conversión ocurre cuando el sistema acompaña la conversación humana. Esta es la página más visitada desde campañas en Latinoamérica.</small></div></section>
<section className="system-composition" id="para-quien"><div className="container"><div className="system-composition__heading"><span className="label-orange">Para quién</span><h2>Cuando vender exige una conversación <em className="font-serif-accent">humana</em>.</h2><p>Negocios donde la venta pasa por una persona, pero el sistema evita que el prospecto se pierda.</p></div><div className="sales-flow-track" aria-label="Flujo comercial"><span>Pauta</span><i>→</i><span>WhatsApp</span><i>→</i><span>CRM</span><i>→</i><span>Venta</span></div></div></section>
<section className="system-composition system-warm"><div className="container"><div className="system-composition__heading"><span className="label-orange">Cómo empieza</span><h2>Probamos el flujo completo con prospectos <em className="font-serif-accent">reales</em>.</h2><p>La aceptación exige trazabilidad, respuesta y asignación funcionando.</p></div><span className="system-deadline">Sistema aceptado en máximo 30 días</span><div className="system-step-grid">{["Pauta, WhatsApp Business API y CRM conectados","Flujo probado con prospectos reales","Todos los prospectos entran al CRM con su origen"].map((texto,index)=><article key={texto}><span>{String(index+1).padStart(2,"0")}</span><p>{texto}</p></article>)}</div></div></section>
<FaqSection items={FAQS}/><GeneralCta />
</main><SiteFooter/></div>}
function SalesFlowError(){const router=useRouter();return <div className="rckt-site tcn-page"><SiteHeader/><main className="band"><div className="container"><div className="form-card" role="alert"><span className="kicker">Sales Flow</span><h1>No pudimos mostrar esta página.</h1><p>Intenta cargarla nuevamente. Si el problema continúa, puedes volver al inicio.</p><div className="form-actions"><button className="btn btn-primary" type="button" onClick={()=>void router.invalidate()}>Intentar de nuevo</button><a className="btn" href="/">Volver al inicio</a></div></div></div></main><SiteFooter/></div>}
