import { createFileRoute,useRouter } from "@tanstack/react-router";
import { BarChart3, CalendarCheck, CalendarDays, Database, Megaphone, MonitorSmartphone, Target, UserRound, Users, Workflow, Wrench } from "lucide-react";
import {SiteFooter,SiteHeader,useSiteMotion} from "@/components/SiteChrome";
import FaqSection,{faqJsonLd,type FaqItem} from "@/components/rckt/FaqSection";
import SystemFinalCta from "@/components/rckt/SystemFinalCta";
import SystemPageHero from "@/components/rckt/SystemPageHero";
const SITE_URL="https://rckt-latam.lovable.app";
const INCLUYE=[{titulo:"Demand",detalle:"Tier según inversión."},{titulo:"Sales Flow",detalle:"Ads, WhatsApp y CRM conectados."},{titulo:"Landing de conversión",detalle:"Con tracking y CRM conectados."},{titulo:"CRM & RevOps",detalle:"El proceso comercial en un solo lugar."},{titulo:"Medición completa",detalle:"Del clic al cierre."},{titulo:"Responsable de cuenta",detalle:"Una persona con autoridad."},{titulo:"Revisión mensual",detalle:"Con decisores, no con coordinadores."},{titulo:"Ciclo de optimización",detalle:"90 días."}];
const ESCALERA=[{label:"Revenue Diagnostic",texto:"Semanas 0-3."},{label:"Demand o Revenue Engine",texto:"Meses 1-6."},{label:"+ Operations",texto:"Meses 6-12."},{label:"Growth OS",texto:"Destino de cuentas maduras, mes 12 en adelante."}];
const INCLUDE_ICONS=[Megaphone,Workflow,MonitorSmartphone,Database,BarChart3,UserRound,CalendarDays,Wrench];
const STATS=[
  {label:"Para quién",detail:"Negocios de captación y cierre",Icon:Users},
  {label:"Setup",detail:"Demand, Sales Flow, landing, CRM y tracking",Icon:Wrench},
  {label:"Compromiso mínimo",detail:"6 meses",Icon:CalendarCheck},
  {label:"Qué mide el éxito",detail:"Costo por cliente adquirido",Icon:Target},
];
const FAQS: FaqItem[]=[
  {question:"¿RCKT garantiza resultados o un número de ventas nuevas al mes?",answer:"No garantizamos ventas, porque no controlamos tu cierre, tu inventario ni tus precios. Garantizamos que en 30 días verás tu embudo completo con datos reales."},
  {question:"¿Puedo contratar Growth OS directamente sin pasar por Revenue Engine primero?",answer:"No. Growth OS es para cuentas maduras que ya llevan tiempo con nosotros; empezamos por Revenue Engine y crecemos con evidencia."},
  {question:"¿Cuál es el compromiso mínimo de tiempo para Revenue Engine?",answer:"6 meses — el sistema necesita un ciclo completo para demostrar resultados."},
  {question:"¿Qué debería ver en mi negocio a los 30, 60 y 90 días de empezar Revenue Engine?",answer:"Día 30: sistema operativo con fuente de verdad. Día 90: revisión de línea base frente a resultado."},
];
export const Route=createFileRoute("/sistemas/revenue-engine")({staticData:{sitemap:true},head:()=>({meta:[{title:"Revenue Engine — RCKT"},{name:"description",content:"El sistema completo de captación a cierre: Demand, Sales Flow, CRM y medición con un solo responsable."},{property:"og:title",content:"Revenue Engine — RCKT"},{property:"og:description",content:"Un solo sistema, un solo responsable y una sola cifra: cuánto cuesta cada cliente nuevo."},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL+"/sistemas/revenue-engine"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:SITE_URL+"/sistemas/revenue-engine"}],scripts:FAQS.length>0?[faqJsonLd(FAQS)]:[]}),component:RevenueEnginePage,errorComponent:RevenueEngineError,notFoundComponent:()=> <RevenueEngineError/>});
function RevenueEnginePage(){useSiteMotion([]);return <div className="rckt-site tcn-page"><main id="top">
<SystemPageHero label="Revenue Engine" title={<>El sistema completo de captación a <em>cierre</em>.</>} promise="Tu pauta, tu WhatsApp y tu CRM hoy son tres cosas separadas que maneja gente distinta. Revenue Engine las convierte en un solo sistema con un solo responsable: nosotros. Tú ves una cifra: cuánto te cuesta cada cliente nuevo."/>
<section className="system-composition system-stats"><div className="container system-stat-grid">{STATS.map(({label,detail,Icon})=><article className="system-stat-card" key={label}><span className="system-icon"><Icon aria-hidden="true"/></span><p className="label-orange">{label}</p><p>{detail}</p></article>)}</div></section>
<section className="system-composition system-warm" id="incluye"><div className="container"><div className="system-composition__heading"><span className="label-orange">Qué incluye</span><h2>Todo el sistema, un solo <em className="font-serif-accent">responsable</em>.</h2><p>De la generación de demanda al cierre, con una fuente de verdad.</p></div><div className="engine-grid">{INCLUYE.map((item,index)=>{const Icon=INCLUDE_ICONS[index];return <article className={index<2?"engine-card engine-card--primary":"engine-card"} key={item.titulo}><span className="system-icon"><Icon aria-hidden="true"/></span><h3>{item.titulo}</h3><p>{item.detalle}</p></article>})}</div></div></section>
<section className="engine-metric-band" id="compromiso"><div className="container"><div><span className="label-on-orange">Compromiso mínimo</span><strong>6 meses</strong><p>Seis meses para demostrar un ciclo completo. El sistema necesita tiempo suficiente para operar, aprender y comparar.</p></div><div><span className="label-on-orange">Cómo se mide</span><strong>1 cifra</strong><p>Costo por cliente adquirido · Valor del cliente frente a lo que costó traerlo · Embudo completo: prospecto → MQL → SQL → cita → oportunidad → venta → margen</p></div></div></section>
<section className="system-composition" id="escalera"><div className="container"><div className="system-composition__heading"><span className="label-orange">Cómo empieza</span><h2>La cuenta crece por etapas, no de golpe.</h2><p>Cada sistema entra cuando la cuenta está lista.</p></div><span className="system-deadline">Escalera de cuenta</span><div className="engine-ladder">{ESCALERA.map((item,index)=><article key={item.label}><span>{String(index+1).padStart(2,"0")}</span><h3>{item.label}</h3><p>{item.texto}</p></article>)}</div><a className="engine-method-link" href="/nosotros/como-trabajamos">Cómo trabajamos →</a></div></section>
<section className="system-composition system-warm"><div className="container"><div className="system-composition__heading"><span className="label-orange">Criterios de aceptación</span><h2>Día 30: sistema operativo. Día 90: resultado contra línea base.</h2><p>La operación se prueba antes de atribuirle un resultado.</p></div><div className="engine-milestones"><article><strong>30</strong><p>Sistema operativo con una sola fuente de verdad.</p></article><article><strong>90</strong><p>Revisión de la línea base frente al resultado.</p></article></div></div></section>
<FaqSection items={FAQS}/><SystemFinalCta/>
</main><SiteFooter/></div>}
function RevenueEngineError(){const router=useRouter();return <div className="rckt-site tcn-page"><SiteHeader/><main className="band"><div className="container"><div className="form-card" role="alert"><span className="kicker">Revenue Engine</span><h1>No pudimos mostrar esta página.</h1><p>Intenta cargarla nuevamente. Si el problema continúa, puedes volver al inicio.</p><div className="form-actions"><button className="btn btn-primary" type="button" onClick={()=>void router.invalidate()}>Intentar de nuevo</button><a className="btn" href="/">Volver al inicio</a></div></div></div></main><SiteFooter/></div>}
