import { createFileRoute,useRouter } from "@tanstack/react-router";
import {SiteFooter,SiteHeader,useSiteMotion} from "@/components/SiteChrome";
import FaqSection,{faqJsonLd} from "@/components/rckt/FaqSection";
import {AcceptanceSteps,CapabilityCards,RuleList} from "@/components/rckt/SystemBlocks";
import SystemFinalCta from "@/components/rckt/SystemFinalCta";
import SystemPageHero from "@/components/rckt/SystemPageHero";
import SystemSection from "@/components/rckt/SystemSection";
import {REVENUE_ENGINE_FAQS} from "@/content/systemFaqs";
const SITE_URL="https://rckt-latam.lovable.app";
const INCLUYE=[{titulo:"Demand",detalle:"Tier según inversión."},{titulo:"Sales Flow",detalle:"Ads, WhatsApp y CRM conectados."},{titulo:"Landing de conversión",detalle:"Con tracking y CRM conectados."},{titulo:"CRM & RevOps",detalle:"El proceso comercial en un solo lugar."},{titulo:"Medición completa",detalle:"Del clic al cierre."},{titulo:"Responsable de cuenta",detalle:"Una persona con autoridad."},{titulo:"Revisión mensual",detalle:"Con decisores, no con coordinadores."},{titulo:"Ciclo de optimización",detalle:"90 días."}];
const ESCALERA=[{label:"Revenue Diagnostic",texto:"Semanas 0-3."},{label:"Demand o Revenue Engine",texto:"Meses 1-6."},{label:"+ Operations",texto:"Meses 6-12."},{label:"Growth OS",texto:"Destino de cuentas maduras, mes 12 en adelante."}];
export const Route=createFileRoute("/sistemas/revenue-engine")({staticData:{sitemap:true},head:()=>({meta:[{title:"Revenue Engine — RCKT"},{name:"description",content:"El sistema completo de captación a cierre: Demand, Sales Flow, CRM y medición con un solo responsable."},{property:"og:title",content:"Revenue Engine — RCKT"},{property:"og:description",content:"Un solo sistema, un solo responsable y una sola cifra: cuánto cuesta cada cliente nuevo."},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL+"/sistemas/revenue-engine"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:SITE_URL+"/sistemas/revenue-engine"}],scripts:[faqJsonLd(REVENUE_ENGINE_FAQS)]}),component:RevenueEnginePage,errorComponent:RevenueEngineError,notFoundComponent:()=> <RevenueEngineError/>});
function RevenueEnginePage(){useSiteMotion([]);return <div className="rckt-site tcn-page"><main id="top">
<SystemPageHero label="Revenue Engine" title={<>El sistema completo de captación a <em>cierre</em>.</>} promise="Tu pauta, tu WhatsApp y tu CRM hoy son tres cosas separadas que maneja gente distinta. Revenue Engine las convierte en un solo sistema con un solo responsable: nosotros. Tú ves una cifra: cuánto te cuesta cada cliente nuevo."/>
<SystemSection num="01." label="El problema" title={<>Tres herramientas separadas producen tres versiones de la <em className="font-serif-accent">verdad</em>.</>} phrase="Pauta, WhatsApp y CRM deben responder por el mismo resultado."><p className="system-section__lead">Tu pauta, tu WhatsApp y tu CRM hoy son tres cosas separadas que maneja gente distinta.</p></SystemSection>
<SystemSection id="incluye" num="02." label="Qué incluye" title={<>Todo el sistema, un solo <em className="font-serif-accent">responsable</em>.</>} phrase="De la generación de demanda al cierre, con una fuente de verdad."><CapabilityCards compact items={INCLUYE}/></SystemSection>
<SystemSection id="compromiso" num="03." label="Compromiso mínimo" title={<>Seis meses para demostrar un ciclo <em className="font-serif-accent">completo</em>.</>} phrase="El sistema necesita tiempo suficiente para operar, aprender y comparar."><div className="system-highlight"><p>Compromiso mínimo: 6 meses.</p></div></SystemSection>
<SystemSection num="04." label="Cómo se mide" title={<>Una cifra: cuánto cuesta cada cliente <em className="font-serif-accent">nuevo</em>.</>} phrase="Del clic al cierre, con definiciones acordadas."><RuleList items={["Costo por cliente adquirido", "Valor del cliente frente a lo que costó traerlo", "Embudo completo: prospecto → MQL → SQL → cita → oportunidad → venta → margen"]}/></SystemSection>
<SystemSection id="escalera" num="05." label="Cómo empieza" title="La cuenta crece por etapas, no de golpe." phrase="Cada sistema entra cuando la cuenta está lista."><AcceptanceSteps plazo="Escalera de cuenta" items={ESCALERA}/><p className="system-note"><a href="/nosotros/como-trabajamos">Cómo trabajamos →</a></p></SystemSection>
<SystemSection num="06." label="Criterios de aceptación" title="Día 30: sistema operativo. Día 90: resultado contra línea base." phrase="La operación se prueba antes de atribuirle un resultado."><AcceptanceSteps items={[{hito:"30",texto:"Sistema operativo con una sola fuente de verdad."},{hito:"90",texto:"Revisión de la línea base frente al resultado."}]}/></SystemSection>
<FaqSection items={REVENUE_ENGINE_FAQS}/><SystemFinalCta/>
</main><SiteFooter/></div>}
function RevenueEngineError(){const router=useRouter();return <div className="rckt-site tcn-page"><SiteHeader/><main className="band"><div className="container"><div className="form-card" role="alert"><span className="kicker">Revenue Engine</span><h1>No pudimos mostrar esta página.</h1><p>Intenta cargarla nuevamente. Si el problema continúa, puedes volver al inicio.</p><div className="form-actions"><button className="btn btn-primary" type="button" onClick={()=>void router.invalidate()}>Intentar de nuevo</button><a className="btn" href="/">Volver al inicio</a></div></div></div></main><SiteFooter/></div>}
