import { createFileRoute, useRouter } from "@tanstack/react-router";
import { SiteFooter, SiteHeader, useSiteMotion } from "@/components/SiteChrome";
import FaqSection,{faqJsonLd} from "@/components/rckt/FaqSection";
import {AcceptanceSteps,CapabilityCards,RuleList} from "@/components/rckt/SystemBlocks";
import SystemFinalCta from "@/components/rckt/SystemFinalCta";
import SystemPageHero from "@/components/rckt/SystemPageHero";
import SystemSection from "@/components/rckt/SystemSection";
import {OPERATIONS_SYSTEM_FAQS} from "@/content/systemFaqs";
const SITE_URL="https://rckt-latam.lovable.app";
const CATALOGO=["Cotizaciones desde WhatsApp o correo","Clasificación y respuesta de solicitudes","Generación y verificación de documentos","Sincronización CRM ↔ ERP","Reporting comercial","Atención post-venta de primer nivel"].map((titulo)=>({titulo,detalle:"Proceso diseñado con trazabilidad y supervisión humana."}));
export const Route=createFileRoute("/sistemas/operations-system")({staticData:{sitemap:true},head:()=>({meta:[{title:"Operations System — RCKT"},{name:"description",content:"Procesos que se ejecutan solos, con supervisión: un Operations Sprint de 6-8 semanas y soporte mensual."},{property:"og:title",content:"Operations System — RCKT"},{property:"og:description",content:"Un proceso repetido cien veces por semana, funcionando solo en ocho semanas, con aprobación humana en lo que importa."},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL+"/sistemas/operations-system"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:SITE_URL+"/sistemas/operations-system"}],scripts:[faqJsonLd(OPERATIONS_SYSTEM_FAQS)]}),component:OperationsPage,errorComponent:OperationsError,notFoundComponent:()=> <OperationsError/>});
function OperationsPage(){useSiteMotion([]);return <div className="rckt-site tcn-page"><main id="top">
<SystemPageHero label="Operations System" title={<>Procesos que se ejecutan solos, con <em>supervisión</em>.</>} promise="Elegimos un proceso que tu equipo repite cien veces por semana, medimos cuánto cuesta hoy, y en ocho semanas lo dejamos funcionando solo, con una persona aprobando lo que importa."/>
<SystemSection num="01." label="El problema" title={<>Repetir cien veces no debería costar cien <em className="font-serif-accent">veces</em>.</>} phrase="Empezamos por un proceso repetitivo, medible y con impacto operativo."><p className="system-section__lead">Elegimos un proceso que tu equipo repite cien veces por semana, medimos cuánto cuesta hoy, y en ocho semanas lo dejamos funcionando solo, con una persona aprobando lo que importa.</p></SystemSection>
<SystemSection id="formato" num="02." label="Formato" title="Un proceso, ocho semanas, una línea base." phrase="Operations Sprint, 6-8 semanas, más soporte mensual."><div className="system-highlight"><p>Operations Sprint, 6-8 semanas, más soporte mensual.</p></div></SystemSection>
<SystemSection id="catalogo" num="03." label="Qué incluye" title={<>Automatizamos procesos con un humano donde <em className="font-serif-accent">importa</em>.</>} phrase="Un catálogo concreto de procesos que hoy consumen tiempo del equipo."><CapabilityCards items={CATALOGO}/></SystemSection>
<SystemSection num="04." label="Qué no incluye" title={<>No automatizamos lo que todavía no tiene <em className="font-serif-accent">dueño</em>.</>} phrase="Sin responsable, acceso y reglas claras, no hay sistema que sostener."><RuleList items={["Procesos sin un dueño nombrado", "Automatizaciones sin línea base", "Decisiones irreversibles sin aprobación humana", "Un chatbot aislado como solución"]}/></SystemSection>
<SystemSection num="05." label="Reglas" title={<>Sin línea base no hay <em className="font-serif-accent">sprint</em>.</>} phrase="El proceso se acepta contra costo, tiempo, excepciones y horas liberadas."><RuleList items={["Medimos el costo actual antes de construir", "Firmamos criterios de aceptación en la semana 2", "Una persona aprueba lo que importa", "Si el piloto no mejora el costo por ejecución, no seguimos"]}/></SystemSection>
<SystemSection id="para-quien" num="06." label="Para quién" title={<>Alto volumen, reglas claras y datos <em className="font-serif-accent">accesibles</em>.</>} phrase="Habla Operaciones o Tecnología, no Mercadeo."><RuleList items={["30-250 empleados", "Procesos manuales de alto volumen", "Un dueño de proceso disponible", "Acceso a sistemas, datos y casos históricos"]}/></SystemSection>
<SystemSection num="07." label="Cómo se mide" title={<>Costo, tiempo, excepciones y horas <em className="font-serif-accent">liberadas</em>.</>} phrase="La aceptación compara el piloto contra la línea base firmada."><AcceptanceSteps plazo="Operations Sprint de 6–8 semanas" items={[{texto:"Línea base de costo y tiempo"},{texto:"Criterios de aceptación firmados en semana 2"},{texto:"Piloto con casos históricos y reales"},{texto:"Comparación contra la línea base"}]}/></SystemSection>
<FaqSection items={OPERATIONS_SYSTEM_FAQS}/><SystemFinalCta/>
</main><SiteFooter/></div>}
function OperationsError(){const router=useRouter();return <div className="rckt-site tcn-page"><SiteHeader/><main className="band"><div className="container"><div className="form-card" role="alert"><span className="kicker">Operations System</span><h1>No pudimos mostrar esta página.</h1><p>Intenta cargarla nuevamente. Si el problema continúa, puedes volver al inicio.</p><div className="form-actions"><button className="btn btn-primary" type="button" onClick={()=>void router.invalidate()}>Intentar de nuevo</button><a className="btn" href="/">Volver al inicio</a></div></div></div></main><SiteFooter/></div>}
