/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RcktEquipoRouteImport } from './routes/rckt-equipo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrabajaConNosotrosRouteImport } from './routes/trabaja-con-nosotros'
import { Route as TrabajaConNosotrosAplicarIdRouteImport } from './routes/trabaja-con-nosotros_.aplicar.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RcktEquipoRoute = RcktEquipoRouteImport.update({
  id: '/rckt-equipo',
  path: '/rckt-equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajaConNosotrosRoute = TrabajaConNosotrosRouteImport.update({
  id: '/trabaja-con-nosotros',
  path: '/trabaja-con-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajaConNosotrosAplicarIdRoute =
  TrabajaConNosotrosAplicarIdRouteImport.update({
    id: '/trabaja-con-nosotros_/aplicar/$id',
    path: '/trabaja-con-nosotros/aplicar/$id',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/rckt-equipo': typeof RcktEquipoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/trabaja-con-nosotros/aplicar/$id': typeof TrabajaConNosotrosAplicarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/rckt-equipo': typeof RcktEquipoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/trabaja-con-nosotros/aplicar/$id': typeof TrabajaConNosotrosAplicarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/privacidad': typeof PrivacidadRoute
  '/rckt-equipo': typeof RcktEquipoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/trabaja-con-nosotros_/aplicar/$id': typeof TrabajaConNosotrosAplicarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/privacidad'
    | '/rckt-equipo'
    | '/sitemap.xml'
    | '/trabaja-con-nosotros'
    | '/trabaja-con-nosotros/aplicar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/privacidad'
    | '/rckt-equipo'
    | '/sitemap.xml'
    | '/trabaja-con-nosotros'
    | '/trabaja-con-nosotros/aplicar/$id'
  id:
    | '__root__'
    | '/'
    | '/aviso-legal'
    | '/cookies'
    | '/privacidad'
    | '/rckt-equipo'
    | '/sitemap.xml'
    | '/trabaja-con-nosotros'
    | '/trabaja-con-nosotros_/aplicar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CookiesRoute: typeof CookiesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RcktEquipoRoute: typeof RcktEquipoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrabajaConNosotrosRoute: typeof TrabajaConNosotrosRoute
  TrabajaConNosotrosAplicarIdRoute: typeof TrabajaConNosotrosAplicarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rckt-equipo': {
      id: '/rckt-equipo'
      path: '/rckt-equipo'
      fullPath: '/rckt-equipo'
      preLoaderRoute: typeof RcktEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabaja-con-nosotros': {
      id: '/trabaja-con-nosotros'
      path: '/trabaja-con-nosotros'
      fullPath: '/trabaja-con-nosotros'
      preLoaderRoute: typeof TrabajaConNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabaja-con-nosotros_/aplicar/$id': {
      id: '/trabaja-con-nosotros_/aplicar/$id'
      path: '/trabaja-con-nosotros/aplicar/$id'
      fullPath: '/trabaja-con-nosotros/aplicar/$id'
      preLoaderRoute: typeof TrabajaConNosotrosAplicarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CookiesRoute: CookiesRoute,
  PrivacidadRoute: PrivacidadRoute,
  RcktEquipoRoute: RcktEquipoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrabajaConNosotrosRoute: TrabajaConNosotrosRoute,
  TrabajaConNosotrosAplicarIdRoute: TrabajaConNosotrosAplicarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
