// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Client-side only: use VITE_ prefixed variables (Vite build-time injection)
  let SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim();
  let SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim();

  // Debug logging (temporary)
  console.log("[SUPABASE DEBUG]", {
    viteUrl: SUPABASE_URL || "(empty)",
    viteKey: SUPABASE_PUBLISHABLE_KEY ? `${SUPABASE_PUBLISHABLE_KEY.substring(0, 10)}...` : "(empty)",
    hasProcess: typeof process !== "undefined",
  });

  // Validate URL format
  if (!SUPABASE_URL || !/^https?:\/\/.+/i.test(SUPABASE_URL)) {
    const message = `[Supabase] Invalid VITE_SUPABASE_URL: ${JSON.stringify(SUPABASE_URL)}. Make sure .env.local has VITE_SUPABASE_URL set correctly.`;
    console.error(message);
    throw new Error(message);
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    const message = `[Supabase] Missing VITE_SUPABASE_PUBLISHABLE_KEY in environment`;
    console.error(message);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
